
services:
  app:
    image: your-image-name
    networks:
      - debrand-network
    volumes:
      - /home/rocky/fieratrisVenticano/volume:/app/data  # Volume to link CSV files
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  debrand-network:
    external: true