services:
  app:
    image: fieratris-venticano
    container_name: fieratris-app
    ports:
      - "3000:3000"
    volumes:
      - ./data:/usr/src/app/data  # Volume per i file CSV dei punteggi
    restart: unless-stopped
    networks:
      - fieratris-network

networks:
  fieratris-network:
    driver: bridge # external: true # in caso si voglia usare una rete personalizzata